### ISSUE TITLE
Schematic for those who are not using Eagle

### ISSUE THREAD

**Issue by fdufnews** [technoblogy/lisp-badge#1]
Hi,
Thanks a lot for this design but can you put a schematic in pdf format for those that are not using eagle.
When comparing the code in this repo and the schematic on technoblogy it seems there are differences (on shiftr for example).
A fast search with a text editor seems to confirm that shiftr is connected to D10-SS. Am I right?
Best regards
fdufnews

**Comment by technoblogy** [comment]
The left and right SHIFT keys both connect between PC7 and GND. The label SHIFTR on D10 on the Eagle schematic is a mistake, and should be removed.

The schematic on Technoblogy was generated from the Eagle schematic, and then tidied up by hand. It corrects some errors that don't affect the PCB. Which one would you like as a PDF?

**Comment by fdufnews** [comment]
Ok, thanks you for the answer.
So the second part of the test at line 3882 is no more necessary
```
  // Check rows and shift keys
  shift = ((PINC & 1<<PINC7) && (PINB & 1<<PINB4)) ? 0 : 1;
```
I am analysing the code because I want to use the keyboard of an Xbox chatpad and the matrix is different from the one you are using.

**Comment by technoblogy** [comment]
You’re correct. The previous version of the circuit had the SHIFT keys on two separate inputs, but I decided to add a piezo speaker on PB4, so that line should change to:

  shift = (PINC & 1<<PINC7) ? 0 : 1;

Also, remove this line in InitKybd():

  PORTB = PORTB | 1<<PINB4;

Thanks for spotting that. I’ll update the code.

Regards,
David

+------------------------------------------------------------+
David Johnson-Davies, Human-Computer Interface Ltd
17 Signet Court, Swanns Road, Cambridge, CB5 8LA, England.

Tel: +44 1223 314934, Fax: +44 1223 462562
Email: david@interface.co.uk, Web: http://www.interface.co.uk/
+------------------------------------------------------------+
